alias stat='git status'
alias add='git add '
alias ac='git add -u && git commit -m'
alias br='git branch '
alias del='git branch -D '
alias com='git commit'
alias diff='git diff'
alias co='git checkout '
alias un='git reset HEAD '
alias undo='git reset HEAD~1'
alias log="git log --pretty=format:'%Cred%h%Creset 👉 %C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias stash='git stash'
alias apply='git stash apply'
alias pull='git pull origin '
alias push='git push origin '
alias got='git '
alias get='git '

alias reload='source ~/.bashrc && source ~/.bash_profile && source ~/.zshrc && clear'
